include ::openstack
include ::openstack::rabbitmq
include ::openstack::mysql
include ::openstack::keystone
include ::openstack::glance
include ::openstack::neutron
include ::openstack::nova
include ::openstack::cinder
include ::openstack::horizon
include ::openstack::provision
